[workspace]
members = [
    "axum-accept",
    "axum-accept-macros",
    "axum-accept-shared",
]
resolver = "2"

[workspace.dependencies]
axum = { version = "0.8", default-features = false }
mediatype = "0.20"
