name: CI

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v*"
    branches:
      - main

jobs:
  rustfmt_check:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo fmt -- --check
  check_versions:
    name: Check versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall -y rust-script
      - run: ./scripts/check-versions.rs
  clippy_check:
    name: Clippy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-all-
      - run: cargo check
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-all-
      - run: cargo test
  publish_on_crates_io:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags') # Only on tags
    needs:
      - rustfmt_check
      - clippy_check
      - test
      - check_versions
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish -p axum-accept-shared --token ${{ secrets.CRATES_IO_TOKEN }}
      - run: cargo publish -p axum-accept-macros --token ${{ secrets.CRATES_IO_TOKEN }}
      - run: cargo publish -p axum-accept --token ${{ secrets.CRATES_IO_TOKEN }}
